{{- if and (not .Values.security.identitySecret.existingSecret) (or .Values.security.oidc.clientSecret .Values.security.activeDirectory.searchBindPassword) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "attune.identitySecretName" . }}
  labels:
    {{- include "attune.labels" . | nindent 4 }}
    app.kubernetes.io/component: identity
type: Opaque
stringData:
  {{- with .Values.security.oidc.clientSecret }}
  ATTUNE__SECURITY__OIDC__CLIENT_SECRET: {{ . | quote }}
  {{- end }}
  {{- with .Values.security.activeDirectory.searchBindPassword }}
  ATTUNE__SECURITY__LDAP__SEARCH_BIND_PASSWORD: {{ . | quote }}
  {{- end }}
{{- end }}
