{{- if eq .Values.storage.mode "object" }}
{{- if .Values.serviceAccounts.api.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "attune.apiServiceAccountName" . | quote }}
  labels:
    {{- include "attune.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- if .Values.serviceAccounts.supervisor.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "attune.supervisorServiceAccountName" . | quote }}
  labels:
    {{- include "attune.labels" . | nindent 4 }}
  {{- with .Values.serviceAccounts.supervisor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
